### ISSUE TITLE
Add more configuration options

### ISSUE THREAD

**Issue by jschaeff** [ome/ansible-role-rsync-server#2]
Hi,

thanks for this nice ansible role. Both usefull and simple, great !

I'd like to set more configuration options:

- port
- use chroot
- max connections
- syslog facility
- max verbosity
- motd file
- timeout
- read only 
- list
- strict modes
- auth users
- hosts allow
- secrets file

Also to split each share on a different file and use the instruction &include 

I'll try to make a PR for this.

**Comment by manics** [comment]
Thanks for your interest! I can think of a few ways to do this:
- Add options individually as you've suggested
- Have a generic key-value dict that allows arbitrary options to be added to the conf file

Regarding splitting/including files, one issue to consider is if you have one file per share and you subsequently modify your config to remove that share the config file will still remain on the system. Looping through shares in a single config file avoids this.

Please do open a PR and we can refine it if necessary.

**Comment by manics** [comment]
Closing as we don't have a requirement for this so won't be implementing it, however we're happy to review PRs.
